global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: mysql
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 47.106.8.44:9104

  - job_name: gets-frontend
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 47.106.8.44:9527

  - job_name: gets-backend
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
    - targets:
      - 47.106.8.44:8081


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']

# - job_name: 'nodeexporter-jp'
#   scrape_interval: 5s
#   static_configs:
#     - targets: ['118.27.4.45:9100']

# - job_name: 'cadvisor-jp'
#   scrape_interval: 5s
#   static_configs:
#     - targets: ['118.27.4.45:8080']
